version: "3.9"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 3233
      POSTGRES_USER: teste_global
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U users"]
      interval: 3s
      timeout: 5s
      retries: 5
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:9000"
  #   depends_on:
  #     db:
  #       condition: service_healthy